wannabe:
  datasource:
    url: jdbc:mariadb://129.154.58.25:3324/wannabe_dev?serverTimezone=UTC&characterEncoding=UTF-8
    username: admin
    password: wannabe0224
    driver-class: org.mariadb.jdbc.Driver