
/**
 * TYPE 	: DML
 * AUTHOR 	: GGUM
 * DATE 	: 2025-03-01
 * DESC 	: <TABLE_NAME> 영역에 원하는 테이블명 넣으면 테이블 전체 컬럼출력.
 * 			  MODEL 객체 생성 또는 myBatis XML파일 생성 시 사용하면 편리합니다~
 */
SELECT
    A.COLUMN_NAME
     , SUBSTR(REPLACE(INITCAP('1'||A.COLUMN_NAME), '_'), 2) AS COLUMN_NAME_CAMEL_CASE
     , '#{' || SUBSTR(REPLACE(INITCAP('1'||A.COLUMN_NAME), '_'), 2) || '}' AS COLUMN_NAME_CAMEL_CASE_IN_MYBATIS
     , B.COMMENTS
FROM
    ALL_TAB_COLUMNS A
        INNER JOIN ALL_COL_COMMENTS B
                   ON A.TABLE_NAME	 = B.TABLE_NAME
                       AND A.COLUMN_NAME = B.COLUMN_NAME
WHERE 1=1
  AND A.OWNER = 'WANNABE_DEV'
  AND A.TABLE_NAME = <TABLE_NAME>
ORDER BY A.COLUMN_ID;
	
	
