INSERT INTO WANNABE_DEV.COMMON_CODE
(CODE_KEY, CODE_NAME, CODE_DESC, INSERT_USER_ID, INSERT_DT)
VALUES('LOG_TYPE', '로그종류', '시스템 로그 유형을 구분하는 코드', 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE
(CODE_KEY, CODE_NAME, CODE_DESC, INSERT_USER_ID, INSERT_DT)
VALUES('USE_YN', '사용여부', '사용 여부를 구분하는 코드', 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE
(CODE_KEY, CODE_NAME, CODE_DESC, INSERT_USER_ID, INSERT_DT)
VALUES('GENDER_CODE', '성별', '성별을 구분하는 코드', 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE
(CODE_KEY, CODE_NAME, CODE_DESC, INSERT_USER_ID, INSERT_DT)
VALUES('AVAIL_STATUS', '상태', '요청에 대한 현재 상태를 나타내는 코드', 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE
(CODE_KEY, CODE_NAME, CODE_DESC, INSERT_USER_ID, INSERT_DT)
VALUES('ITEM_TYPE', '아이템유형', '아이템 종류를 구분하는 코드', 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE
(CODE_KEY, CODE_NAME, CODE_DESC, INSERT_USER_ID, INSERT_DT)
VALUES('PRODUCT_TYPE', '상품종류', '상품의 종류를 구분하는 코드', 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE
(CODE_KEY, CODE_NAME, CODE_DESC, INSERT_USER_ID, INSERT_DT)
VALUES('PAYMENT_TYPE', '결제종류', '결제 방식을 구분하는 코드', 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE
(CODE_KEY, CODE_NAME, CODE_DESC, INSERT_USER_ID, INSERT_DT)
VALUES('HOMPIE_CONFIG_CODE', '미니홈피설정', '미니홈피 설정 종류를 구분하는 코드', 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE
(CODE_KEY, CODE_NAME, CODE_DESC, INSERT_USER_ID, INSERT_DT)
VALUES('HOMPIE_MENU_CODE', '미니홈피메뉴', '미니홈피 메뉴를 구분하는 코드', 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE
(CODE_KEY, CODE_NAME, CODE_DESC, INSERT_USER_ID, INSERT_DT)
VALUES('FACE_DIRECTION_CODE', '미니미 방향', '미니미가 바라보는 방향을 구분하는 코드', 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE
(CODE_KEY, CODE_NAME, CODE_DESC, INSERT_USER_ID, INSERT_DT)
VALUES('NOTICE_TYPE', '알림 종류', '공지사항 게시판의 알림 종류를 구분하는 코드', 'SYSTEM_ADMIN', SYSDATE);


INSERT INTO WANNABE_DEV.COMMON_CODE_DETAIL (CODE_KEY,CODE_ID,CODE_NAME, SORT_SEQ, INSERT_USER_ID, INSERT_DT)
	VALUES ('LOG_TYPE', 'SYS', '시스템', 0, 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE_DETAIL (CODE_KEY,CODE_ID,CODE_NAME, SORT_SEQ, INSERT_USER_ID, INSERT_DT)
	VALUES ('LOG_TYPE', 'ERR', 'ERROR', 1, 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE_DETAIL (CODE_KEY,CODE_ID,CODE_NAME, SORT_SEQ, INSERT_USER_ID, INSERT_DT)
	VALUES ('LOG_TYPE', 'ART', 'ALERT', 2, 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE_DETAIL (CODE_KEY,CODE_ID,CODE_NAME, SORT_SEQ, INSERT_USER_ID, INSERT_DT)
	VALUES ('USE_YN', 'Y', '사용', 0, 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE_DETAIL (CODE_KEY,CODE_ID,CODE_NAME, SORT_SEQ, INSERT_USER_ID, INSERT_DT)
	VALUES ('USE_YN', 'N', '사용안함', 1, 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE_DETAIL (CODE_KEY,CODE_ID,CODE_NAME, SORT_SEQ, INSERT_USER_ID, INSERT_DT)
	VALUES ('GENDER_CODE', 'M', '남자', 0, 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE_DETAIL (CODE_KEY,CODE_ID,CODE_NAME, SORT_SEQ, INSERT_USER_ID, INSERT_DT)
	VALUES ('GENDER_CODE', 'F', '여자', 1, 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE_DETAIL (CODE_KEY,CODE_ID,CODE_NAME, SORT_SEQ, INSERT_USER_ID, INSERT_DT)
	VALUES ('AVAIL_STATUS', '01', '요청', 0, 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE_DETAIL (CODE_KEY,CODE_ID,CODE_NAME, SORT_SEQ, INSERT_USER_ID, INSERT_DT)
	VALUES ('AVAIL_STATUS', '02', '수락', 1, 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE_DETAIL (CODE_KEY,CODE_ID,CODE_NAME, SORT_SEQ, INSERT_USER_ID, INSERT_DT)
	VALUES ('AVAIL_STATUS', '03', '거절', 2, 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE_DETAIL (CODE_KEY,CODE_ID,CODE_NAME, SORT_SEQ, INSERT_USER_ID, INSERT_DT)
	VALUES ('AVAIL_STATUS', '11', '사용전', 3, 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE_DETAIL (CODE_KEY,CODE_ID,CODE_NAME, SORT_SEQ, INSERT_USER_ID, INSERT_DT)
	VALUES ('AVAIL_STATUS', '12', '보유중', 4, 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE_DETAIL (CODE_KEY,CODE_ID,CODE_NAME, SORT_SEQ, INSERT_USER_ID, INSERT_DT)
	VALUES ('AVAIL_STATUS', '13', '만료', 5, 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE_DETAIL (CODE_KEY,CODE_ID,CODE_NAME, SORT_SEQ, INSERT_USER_ID, INSERT_DT)
	VALUES ('AVAIL_STATUS', '21', '결제전', 6, 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE_DETAIL (CODE_KEY,CODE_ID,CODE_NAME, SORT_SEQ, INSERT_USER_ID, INSERT_DT)
	VALUES ('AVAIL_STATUS', '22', '결제완료', 7, 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE_DETAIL (CODE_KEY,CODE_ID,CODE_NAME, SORT_SEQ, INSERT_USER_ID, INSERT_DT)
	VALUES ('AVAIL_STATUS', '23', '환불요청', 8, 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE_DETAIL (CODE_KEY,CODE_ID,CODE_NAME, SORT_SEQ, INSERT_USER_ID, INSERT_DT)
	VALUES ('AVAIL_STATUS', '24', '환불완료', 9, 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE_DETAIL (CODE_KEY,CODE_ID,CODE_NAME, SORT_SEQ, INSERT_USER_ID, INSERT_DT)
	VALUES ('AVAIL_STATUS', '25', '환불실패', 10, 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE_DETAIL (CODE_KEY,CODE_ID,CODE_NAME, SORT_SEQ, INSERT_USER_ID, INSERT_DT)
	VALUES ('AVAIL_STATUS', '31', '모두공개', 11, 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE_DETAIL (CODE_KEY,CODE_ID,CODE_NAME, SORT_SEQ, INSERT_USER_ID, INSERT_DT)
	VALUES ('AVAIL_STATUS', '32', '일촌공개', 12, 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE_DETAIL (CODE_KEY,CODE_ID,CODE_NAME, SORT_SEQ, INSERT_USER_ID, INSERT_DT)
	VALUES ('AVAIL_STATUS', '33', '나만보기', 13, 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE_DETAIL (CODE_KEY,CODE_ID,CODE_NAME, SORT_SEQ, INSERT_USER_ID, INSERT_DT)
	VALUES ('AVAIL_STATUS', '34', '사용하지않기', 14, 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE_DETAIL (CODE_KEY,CODE_ID,CODE_NAME, SORT_SEQ, INSERT_USER_ID, INSERT_DT)
	VALUES ('ITEM_TYPE', 'M', '배경음악', 1, 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE_DETAIL (CODE_KEY,CODE_ID,CODE_NAME, SORT_SEQ, INSERT_USER_ID, INSERT_DT)
	VALUES ('ITEM_TYPE', 'P', '상품', 2, 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE_DETAIL (CODE_KEY,CODE_ID,CODE_NAME, SORT_SEQ, INSERT_USER_ID, INSERT_DT)
	VALUES ('PRODUCT_TYPE', '01', '얼굴', 1, 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE_DETAIL (CODE_KEY,CODE_ID,CODE_NAME, SORT_SEQ, INSERT_USER_ID, INSERT_DT)
	VALUES ('PRODUCT_TYPE', '02', '헤어', 2, 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE_DETAIL (CODE_KEY,CODE_ID,CODE_NAME, SORT_SEQ, INSERT_USER_ID, INSERT_DT)
	VALUES ('PRODUCT_TYPE', '03', '의상', 3, 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE_DETAIL (CODE_KEY,CODE_ID,CODE_NAME, SORT_SEQ, INSERT_USER_ID, INSERT_DT)
	VALUES ('PRODUCT_TYPE', '10', '배경사진', 4, 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE_DETAIL (CODE_KEY,CODE_ID,CODE_NAME, SORT_SEQ, INSERT_USER_ID, INSERT_DT)
	VALUES ('PRODUCT_TYPE', '11', '메뉴색상', 5, 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE_DETAIL (CODE_KEY,CODE_ID,CODE_NAME, SORT_SEQ, INSERT_USER_ID, INSERT_DT)
	VALUES ('PRODUCT_TYPE', '12', '글자색상', 6, 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE_DETAIL (CODE_KEY,CODE_ID,CODE_NAME, SORT_SEQ, INSERT_USER_ID, INSERT_DT)
	VALUES ('PRODUCT_TYPE', '13', '폰트', 7, 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE_DETAIL (CODE_KEY,CODE_ID,CODE_NAME, SORT_SEQ, INSERT_USER_ID, INSERT_DT)
	VALUES ('PAYMENT_TYPE', '01', '무통장입금', 0, 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE_DETAIL (CODE_KEY,CODE_ID,CODE_NAME, SORT_SEQ, INSERT_USER_ID, INSERT_DT)
	VALUES ('PAYMENT_TYPE', '02', '신용카드', 1, 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE_DETAIL (CODE_KEY,CODE_ID,CODE_NAME, SORT_SEQ, INSERT_USER_ID, INSERT_DT)
	VALUES ('PAYMENT_TYPE', '03', '카카오페이', 2, 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE_DETAIL (CODE_KEY,CODE_ID,CODE_NAME, SORT_SEQ, INSERT_USER_ID, INSERT_DT)
	VALUES ('PAYMENT_TYPE', '04', '네이버페이', 3, 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE_DETAIL (CODE_KEY,CODE_ID,CODE_NAME, SORT_SEQ, INSERT_USER_ID, INSERT_DT)
	VALUES ('PAYMENT_TYPE', '05', '토스', 4, 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE_DETAIL (CODE_KEY,CODE_ID,CODE_NAME, SORT_SEQ, INSERT_USER_ID, INSERT_DT)
	VALUES ('HOMPIE_CONFIG_CODE', '01', '프로필사진URL', 0, 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE_DETAIL (CODE_KEY,CODE_ID,CODE_NAME, SORT_SEQ, INSERT_USER_ID, INSERT_DT)
	VALUES ('HOMPIE_CONFIG_CODE', '02', '소개글', 1, 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE_DETAIL (CODE_KEY,CODE_ID,CODE_NAME, SORT_SEQ, INSERT_USER_ID, INSERT_DT)
	VALUES ('HOMPIE_CONFIG_CODE', '03', '일촌평사용여부', 2, 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE_DETAIL (CODE_KEY,CODE_ID,CODE_NAME, SORT_SEQ, INSERT_USER_ID, INSERT_DT)
	VALUES ('HOMPIE_MENU_CODE', '01', '다이어리', 0, 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE_DETAIL (CODE_KEY,CODE_ID,CODE_NAME, SORT_SEQ, INSERT_USER_ID, INSERT_DT)
	VALUES ('HOMPIE_MENU_CODE', '02', '쥬크박스', 1, 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE_DETAIL (CODE_KEY,CODE_ID,CODE_NAME, SORT_SEQ, INSERT_USER_ID, INSERT_DT)
	VALUES ('HOMPIE_MENU_CODE', '03', '사진첩', 2, 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE_DETAIL (CODE_KEY,CODE_ID,CODE_NAME, SORT_SEQ, INSERT_USER_ID, INSERT_DT)
	VALUES ('HOMPIE_MENU_CODE', '04', '게시판', 3, 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE_DETAIL (CODE_KEY,CODE_ID,CODE_NAME, SORT_SEQ, INSERT_USER_ID, INSERT_DT)
	VALUES ('HOMPIE_MENU_CODE', '05', '방명록', 4, 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE_DETAIL (CODE_KEY,CODE_ID,CODE_NAME, SORT_SEQ, INSERT_USER_ID, INSERT_DT)
	VALUES ('FACE_DIRECTION_CODE', '01', '정면', 0, 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE_DETAIL (CODE_KEY,CODE_ID,CODE_NAME, SORT_SEQ, INSERT_USER_ID, INSERT_DT)
	VALUES ('FACE_DIRECTION_CODE', '02', '왼쪽보기', 1, 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE_DETAIL (CODE_KEY,CODE_ID,CODE_NAME, SORT_SEQ, INSERT_USER_ID, INSERT_DT)
	VALUES ('FACE_DIRECTION_CODE', '03', '오른쪽보기', 2, 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE_DETAIL (CODE_KEY,CODE_ID,CODE_NAME, SORT_SEQ, INSERT_USER_ID, INSERT_DT)
	VALUES ('FACE_DIRECTION_CODE', '04', '뒤돌기', 2, 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE_DETAIL (CODE_KEY,CODE_ID,CODE_NAME, SORT_SEQ, INSERT_USER_ID, INSERT_DT)
	VALUES ('NOTICE_TYPE', '01', '공지사항', 0, 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE_DETAIL (CODE_KEY,CODE_ID,CODE_NAME, SORT_SEQ, INSERT_USER_ID, INSERT_DT)
	VALUES ('NOTICE_TYPE', '02', '팝업공지', 1, 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE_DETAIL (CODE_KEY,CODE_ID,CODE_NAME, SORT_SEQ, INSERT_USER_ID, INSERT_DT)
	VALUES ('NOTICE_TYPE', '11', '전체쪽지', 2, 'SYSTEM_ADMIN', SYSDATE);

INSERT INTO WANNABE_DEV.COMMON_CODE_DETAIL (CODE_KEY,CODE_ID,CODE_NAME, SORT_SEQ, INSERT_USER_ID, INSERT_DT)
	VALUES ('NOTICE_TYPE', '12', '관리자쪽지', 3, 'SYSTEM_ADMIN', SYSDATE);

